spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-qr
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 34743777217A25432A462D4A614E645267556A586E3272357538782F413F4428
      expiration: 86400000 # a day: 86400000  a min: 60000
springdoc:
  swagger-ui:
    persist-authorization: true
whiteList:
  /v3/api-docs/*,
  /v3/api-docs, /swagger-ui/*,
  /api/v1/auth/**,
  /api/v1/qr-codes/code/**
